import csv
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "config" / "models.yaml"
DBT_SEED = ROOT / "dbt" / "seeds" / "models.csv"
TS_OUT = ROOT / "dashboard" / "src" / "lib" / "models.ts"


def load_models() -> list[dict]:
    if not SOURCE.exists():
        print(f"error: {SOURCE.relative_to(ROOT)} not found", file=sys.stderr)
        sys.exit(1)

    raw = yaml.safe_load(SOURCE.read_text(encoding="utf-8"))
    models = (raw or {}).get("models")
    if not isinstance(models, list) or not models:
        print(
            f"error: {SOURCE.relative_to(ROOT)} must contain a non-empty `models` list",
            file=sys.stderr,
        )
        sys.exit(1)
    return models


def make_regex_pattern(model: str) -> str:
    normalised = (
        model.replace(" V ", r"\s?V?\s?")
             .replace(" X ", r"\s?X?\s?")
             .replace(" ", r"[\sv-]*")
             .replace(".", r"[\s.-]*")
    )
    normalised = re.sub(r"(\d)(\s+)", r"\1(?:\\.\\d)*\2", normalised)
    return r"(?i)\b" + normalised + r"(?:v\d)*\b"


def write_dbt_seed(models: list[dict]) -> None:
    DBT_SEED.parent.mkdir(parents=True, exist_ok=True)

    with DBT_SEED.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["brand", "model", "is_specific_family", "pattern"])

        for entry in models:
            brand = entry["brand"]
            families = entry.get("families") or []
            seen_brand = False
            for family in families:
                if family == brand:
                    seen_brand = True
                w.writerow([brand, family, True, make_regex_pattern(family)])

            if not seen_brand:
                w.writerow([brand, brand, False, make_regex_pattern(brand)])

    print(f"wrote {DBT_SEED.relative_to(ROOT)}")


def write_ts(models: list[dict]) -> None:
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "// AUTO-GENERATED by scripts/generate_model_list.py - DO NOT EDIT.",
        "// Source: config/models.yaml",
        "// Regenerate: make generate",
        "",
        "export interface ModelFamily {",
        "  readonly name: string;",
        "}",
        "",
        "export interface Model {",
        "  readonly brand: string;",
        "  readonly families: readonly ModelFamily[];",
        "}",
        "",
        "export const MODEL_LIST: readonly Model[] = [",
    ]

    for entry in models:
        lines.append("  {")
        lines.append(f"    brand: {entry['brand']!r},")
        families = entry.get("families") or []
        if families:
            lines.append("    families: [")
            for family in families:
                lines.append(f"      {{ name: {family!r} }},")
            lines.append("    ],")
        else:
            lines.append("    families: [],")
        lines.append("  },")

    lines.append("];")
    lines.append("")
    lines.append("export const MODEL_BRANDS = MODEL_LIST.map((m) => m.brand);")
    lines.append("")

    TS_OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {TS_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    models = load_models()
    write_dbt_seed(models)
    write_ts(models)
