// AUTO-GENERATED by scripts/generate_model_list.py - DO NOT EDIT.
// Source: config/models.yaml
// Regenerate: make generate

export interface ModelFamily {
  readonly name: string;
}

export interface Model {
  readonly brand: string;
  readonly families: readonly ModelFamily[];
}

export const MODEL_LIST: readonly Model[] = [
  {
    brand: 'DeepSeek',
    families: [
      { name: 'DeepSeek V4' },
    ],
  },
  {
    brand: 'Qwen',
    families: [
      { name: 'Qwen 3.8 Flash Next' },
      { name: 'Qwen 3.8' },
      { name: 'Qwen 3.6' },
      { name: 'Qwen 3.5' },
      { name: 'Qwen Agent World' },
      { name: 'Qwen Image Bench' },
    ],
  },
  {
    brand: 'Nemotron',
    families: [
      { name: 'Nemotron 3' },
      { name: 'Cosmos 3' },
    ],
  },
  {
    brand: 'Gemma',
    families: [
      { name: 'Gemma 4 QAT' },
      { name: 'Gemma 4' },
    ],
  },
  {
    brand: 'Phi',
    families: [
      { name: 'Mage' },
      { name: 'MagneticBrain' },
      { name: 'FrogBoss' },
      { name: 'Fara 1.5' },
      { name: 'Phi 4' },
    ],
  },
  {
    brand: 'GLM',
    families: [
      { name: 'GLM 5.3' },
      { name: 'GLM 5.2' },
      { name: 'GLM 5.1' },
      { name: 'GLM 5' },
    ],
  },
  {
    brand: 'Mistral',
    families: [
      { name: 'Devstral 2' },
      { name: 'Ministral 3' },
      { name: 'Mistral Large 3' },
      { name: 'Mistral Medium 3.5' },
      { name: 'Mistral Small 4' },
    ],
  },
  {
    brand: 'Hy',
    families: [
      { name: 'Hy 4 preview' },
      { name: 'Hy 3 preview' },
      { name: 'Hy 3' },
      { name: 'Hy MT 2' },
    ],
  },
  {
    brand: 'Olmo',
    families: [
      { name: 'Emo' },
      { name: 'Tmax' },
      { name: 'Sera' },
      { name: 'Bolmo' },
      { name: 'Olmo Hybrid' },
      { name: 'Olmo 3.1' },
      { name: 'Olmo 3' },
    ],
  },
  {
    brand: 'Granite',
    families: [
      { name: 'Granite 4.2' },
      { name: 'Granite 4.1' },
    ],
  },
  {
    brand: 'LFM',
    families: [
      { name: 'LFM 2.5 VL' },
      { name: 'LFM 2.5' },
      { name: 'LFM 2' },
      { name: 'LFM JP' },
    ],
  },
  {
    brand: 'MiniCPM',
    families: [
      { name: 'MiniCPM 5' },
      { name: 'BitCPM CANN' },
      { name: 'MiniCPM V 4.6' },
    ],
  },
  {
    brand: 'MiMo',
    families: [
      { name: 'MiMo V 2 Flash' },
      { name: 'MiMo V 2.6' },
      { name: 'MiMo V 2.5' },
    ],
  },
  {
    brand: 'Bonsai',
    families: [
      { name: 'Ternary Bonsai 2' },
      { name: 'Ternary Bonsai' },
      { name: 'Bonsai 27B' },
    ],
  },
  {
    brand: 'Ornith',
    families: [
      { name: 'Ornith 1.5' },
      { name: 'Ornith 1' },
    ],
  },
  {
    brand: 'Ling',
    families: [
      { name: 'Ling 3 Flash Fin' },
      { name: 'Ling 3' },
      { name: 'Ling 2.6' },
      { name: 'LLaDA 2.2' },
    ],
  },
  {
    brand: 'Muse Glimmer',
    families: [
      { name: 'Muse Glimmer' },
    ],
  },
  {
    brand: 'Laguna',
    families: [
      { name: 'Laguna M' },
      { name: 'Laguna S 2.1' },
      { name: 'Laguna XS 2.1' },
      { name: 'Laguna XS 2' },
    ],
  },
  {
    brand: 'Nanbeige',
    families: [
      { name: 'Nanbeige 4.2' },
      { name: 'Nanbeige 4' },
    ],
  },
  {
    brand: 'Falcon',
    families: [
      { name: 'Falcon H1 Tiny' },
      { name: 'Falcon H1' },
    ],
  },
  {
    brand: 'K2',
    families: [
      { name: 'K2 Horizon' },
    ],
  },
  {
    brand: 'Spark',
    families: [
      { name: 'Spark X 2.5' },
    ],
  },
  {
    brand: 'KAT',
    families: [
      { name: 'KAT Coder' },
    ],
  },
  {
    brand: 'Laya',
    families: [
      { name: 'Laya' },
    ],
  },
  {
    brand: 'Swift',
    families: [
      { name: 'Swift Flash Next' },
      { name: 'Swift Bonsai 2' },
      { name: 'Swift 1.5' },
      { name: 'Swift 27B' },
    ],
  },
  {
    brand: 'Xing',
    families: [
      { name: 'Xing 4' },
    ],
  },
  {
    brand: 'Hemmingway',
    families: [
      { name: 'Hemmingway' },
    ],
  },
  {
    brand: 'ZDTaichu',
    families: [
      { name: 'ZDTaichu 5' },
    ],
  },
];

export const MODEL_BRANDS = MODEL_LIST.map((m) => m.brand);
